import { ContextState, WorkSession, TabItem } from '../types/context';

export const INITIAL_OPEN_TABS: TabItem[] = [
  {
    id: 'tab-1',
    title: 'Firebase Documentation — Authenticate with Custom Claims',
    url: 'https://firebase.google.com/docs/auth/admin/custom-claims',
    domain: 'firebase.google.com',
    category: 'docs',
    domainCategory: 'development',
    isActive: true,
    timeSpentSeconds: 420,
    lastActivatedAt: new Date().toISOString(),
  },
  {
    id: 'tab-2',
    title: 'GitHub Repository — smart-civic-reporter / auth-middleware.ts',
    url: 'https://github.com/civic-reporter/core-app/blob/main/src/auth.ts',
    domain: 'github.com',
    category: 'repo',
    domainCategory: 'development',
    isActive: false,
    timeSpentSeconds: 680,
  },
  {
    id: 'tab-3',
    title: 'React Documentation — useEffect and cleanup subscriptions',
    url: 'https://react.dev/reference/react/useEffect',
    domain: 'react.dev',
    category: 'docs',
    domainCategory: 'development',
    isActive: false,
    timeSpentSeconds: 190,
  },
  {
    id: 'tab-4',
    title: 'Stack Overflow — Refreshing Firebase Auth ID tokens automatically',
    url: 'https://stackoverflow.com/questions/63219481/firebase-auth-token-refresh-strategy',
    domain: 'stackoverflow.com',
    category: 'qa',
    domainCategory: 'development',
    isActive: false,
    timeSpentSeconds: 95,
  },
];

export const RECENT_SESSIONS: WorkSession[] = [
  {
    id: 'sess-101',
    projectName: 'Smart Civic Reporter',
    currentTask: 'Firebase Authentication',
    contextScore: 87,
    startedAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    lastActiveAt: 'Just now',
    durationMinutes: 48,
    openTabs: INITIAL_OPEN_TABS,
    summary: 'Configuring Firebase token validation in Next.js middleware and reviewing admin custom claims.',
    tags: ['Auth', 'Firebase', 'Security', 'React'],
    switchCount: 3,
    isCurrent: true,
  },
  {
    id: 'sess-102',
    projectName: 'FinTrack AI Dashboard',
    currentTask: 'Stripe Webhooks & Invoice Reconciliation',
    contextScore: 92,
    startedAt: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    lastActiveAt: '3 hours ago',
    durationMinutes: 74,
    openTabs: [
      {
        id: 'tab-ft-1',
        title: 'Stripe Docs — Handling Webhooks with Idempotency',
        url: 'https://stripe.com/docs/webhooks',
        domain: 'stripe.com',
        category: 'docs',
        domainCategory: 'development',
      },
      {
        id: 'tab-ft-2',
        title: 'GitHub — fintrack-ai / api / stripe-handler.ts',
        url: 'https://github.com/fintrack/api/pull/42',
        domain: 'github.com',
        category: 'repo',
        domainCategory: 'development',
      },
      {
        id: 'tab-ft-3',
        title: 'Prisma Schema — Transactions & Webhook Events',
        url: 'https://prisma.io/docs/concepts/components/prisma-schema',
        domain: 'prisma.io',
        category: 'docs',
        domainCategory: 'development',
      },
    ],
    summary: 'Resolved race condition in customer subscription renewal events and idempotency keys.',
    tags: ['Payments', 'Stripe', 'NodeJS'],
    switchCount: 1,
    isCurrent: false,
  },
  {
    id: 'sess-103',
    projectName: 'MedVitals Wearable Telemetry',
    currentTask: 'WebSockets Real-time Heart Rate Streamer',
    contextScore: 78,
    startedAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    lastActiveAt: 'Yesterday',
    durationMinutes: 110,
    openTabs: [
      {
        id: 'tab-mv-1',
        title: 'Socket.IO — Connection State Recovery in v4.6',
        url: 'https://socket.io/docs/v4/connection-state-recovery',
        domain: 'socket.io',
        category: 'docs',
        domainCategory: 'development',
      },
      {
        id: 'tab-mv-2',
        title: 'RxJS — bufferTime and throttleTime operators',
        url: 'https://rxjs.dev/api/operators/throttleTime',
        domain: 'rxjs.dev',
        category: 'docs',
        domainCategory: 'development',
      },
    ],
    summary: 'Optimized high-frequency Bluetooth telemetry ingestion with backpressure throttling.',
    tags: ['IoT', 'WebSockets', 'RxJS'],
    switchCount: 5,
    isCurrent: false,
  },
];

export const INITIAL_CONTEXT_STATE: ContextState = {
  activeProject: 'Smart Civic Reporter',
  currentTask: 'Firebase Authentication',
  contextScore: 87,
  focusState: 'Deep Work',
  switchesToday: 4,
  deepWorkMinutes: 142,
  privacyMode: 'local_only',
  openTabs: INITIAL_OPEN_TABS,
  recentSessions: RECENT_SESSIONS,
  contextSwitchEvents: [],
  tabGroups: [
    {
      groupName: 'Development',
      tabs: INITIAL_OPEN_TABS,
      primaryCategory: 'development',
      confidence: 92,
    },
  ],
  sessionStartTime: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
  lastActivityTime: new Date().toISOString(),
};
