import { ContextState, WorkSession, TabItem, ProjectHistory, PrivacySettings } from '../types/context';

export const INITIAL_OPEN_TABS: TabItem[] = [
  {
    id: 'tab-1',
    title: 'Firebase Documentation — Authenticate with Custom Claims',
    url: 'https://firebase.google.com/docs/auth/admin/custom-claims',
    domain: 'firebase.google.com',
    category: 'docs',
    domainCategory: 'development',
    isActive: true,
    timeSpentSeconds: 420,
    lastActivatedAt: new Date().toISOString(),
  },
  {
    id: 'tab-2',
    title: 'GitHub Repository — smart-civic-reporter / auth-middleware.ts',
    url: 'https://github.com/civic-reporter/core-app/blob/main/src/auth.ts',
    domain: 'github.com',
    category: 'repo',
    domainCategory: 'development',
    isActive: false,
    timeSpentSeconds: 680,
  },
  {
    id: 'tab-3',
    title: 'React Documentation — useEffect and cleanup subscriptions',
    url: 'https://react.dev/reference/react/useEffect',
    domain: 'react.dev',
    category: 'docs',
    domainCategory: 'development',
    isActive: false,
    timeSpentSeconds: 190,
  },
  {
    id: 'tab-4',
    title: 'Stack Overflow — Refreshing Firebase Auth ID tokens automatically',
    url: 'https://stackoverflow.com/questions/63219481/firebase-auth-token-refresh-strategy',
    domain: 'stackoverflow.com',
    category: 'qa',
    domainCategory: 'development',
    isActive: false,
    timeSpentSeconds: 95,
  },
];

export const RECENT_SESSIONS: WorkSession[] = [
  {
    id: 'sess-101',
    projectName: 'Smart Civic Reporter',
    currentTask: 'Firebase Authentication',
    contextScore: 87,
    startedAt: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    lastActiveAt: 'Just now',
    durationMinutes: 48,
    openTabs: INITIAL_OPEN_TABS,
    summary: 'Configuring Firebase token validation in Next.js middleware and reviewing admin custom claims.',
    tags: ['Auth', 'Firebase', 'Security', 'React'],
    switchCount: 3,
    isCurrent: true,
    suggestedNextStep: 'Configure the Google OAuth provider in Firebase Console and test the sign-in flow.',
    unfinishedWork: 'Google OAuth provider configuration is incomplete. The Firebase project is created but the OAuth consent screen needs setup.',
    timeline: [
      {
        id: 'tl-1',
        time: '10:15',
        label: 'Started session',
        description: 'Opened Firebase documentation',
        icon: 'start',
        domain: 'firebase.google.com',
      },
      {
        id: 'tl-2',
        time: '10:25',
        label: 'Opened GitHub',
        description: 'Reviewed auth-middleware.ts implementation',
        icon: 'code',
        domain: 'github.com',
      },
      {
        id: 'tl-3',
        time: '10:38',
        label: 'Debugged OAuth flow',
        description: 'Checked useEffect cleanup in React docs',
        icon: 'debug',
        domain: 'react.dev',
      },
      {
        id: 'tl-4',
        time: '10:51',
        label: 'Researched token refresh',
        description: 'Viewed Stack Overflow for ID token strategy',
        icon: 'docs',
        domain: 'stackoverflow.com',
      },
      {
        id: 'tl-5',
        time: '11:02',
        label: 'Context switch detected',
        description: 'Switched from Firebase to GitHub',
        icon: 'switch',
      },
    ],
  },
  {
    id: 'sess-102',
    projectName: 'FinTrack AI Dashboard',
    currentTask: 'Stripe Webhooks & Invoice Reconciliation',
    contextScore: 92,
    startedAt: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    lastActiveAt: '3 hours ago',
    durationMinutes: 74,
    openTabs: [
      {
        id: 'tab-ft-1',
        title: 'Stripe Docs — Handling Webhooks with Idempotency',
        url: 'https://stripe.com/docs/webhooks',
        domain: 'stripe.com',
        category: 'docs',
        domainCategory: 'development',
      },
      {
        id: 'tab-ft-2',
        title: 'GitHub — fintrack-ai / api / stripe-handler.ts',
        url: 'https://github.com/fintrack/api/pull/42',
        domain: 'github.com',
        category: 'repo',
        domainCategory: 'development',
      },
      {
        id: 'tab-ft-3',
        title: 'Prisma Schema — Transactions & Webhook Events',
        url: 'https://prisma.io/docs/concepts/components/prisma-schema',
        domain: 'prisma.io',
        category: 'docs',
        domainCategory: 'development',
      },
    ],
    summary: 'Resolved race condition in customer subscription renewal events and idempotency keys.',
    tags: ['Payments', 'Stripe', 'NodeJS'],
    switchCount: 1,
    isCurrent: false,
    suggestedNextStep: 'Write unit tests for the idempotency key validation logic.',
    unfinishedWork: 'Webhook retry logic needs a dead-letter queue for failed events.',
    timeline: [
      {
        id: 'tl-ft-1',
        time: '07:10',
        label: 'Started session',
        description: 'Opened Stripe webhook documentation',
        icon: 'start',
        domain: 'stripe.com',
      },
      {
        id: 'tl-ft-2',
        time: '07:22',
        label: 'Code review',
        description: 'Reviewed PR #42 for stripe-handler.ts',
        icon: 'code',
        domain: 'github.com',
      },
      {
        id: 'tl-ft-3',
        time: '07:45',
        label: 'Schema update',
        description: 'Updated Prisma schema for webhook events',
        icon: 'docs',
        domain: 'prisma.io',
      },
    ],
  },
  {
    id: 'sess-103',
    projectName: 'MedVitals Wearable Telemetry',
    currentTask: 'WebSockets Real-time Heart Rate Streamer',
    contextScore: 78,
    startedAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    lastActiveAt: 'Yesterday',
    durationMinutes: 110,
    openTabs: [
      {
        id: 'tab-mv-1',
        title: 'Socket.IO — Connection State Recovery in v4.6',
        url: 'https://socket.io/docs/v4/connection-state-recovery',
        domain: 'socket.io',
        category: 'docs',
        domainCategory: 'development',
      },
      {
        id: 'tab-mv-2',
        title: 'RxJS — bufferTime and throttleTime operators',
        url: 'https://rxjs.dev/api/operators/throttleTime',
        domain: 'rxjs.dev',
        category: 'docs',
        domainCategory: 'development',
      },
    ],
    summary: 'Optimized high-frequency Bluetooth telemetry ingestion with backpressure throttling.',
    tags: ['IoT', 'WebSockets', 'RxJS'],
    switchCount: 5,
    isCurrent: false,
    suggestedNextStep: 'Implement connection state recovery for dropped WebSocket connections.',
    unfinishedWork: 'Backpressure handling is partially implemented; buffer overflow on high-frequency streams needs testing.',
    timeline: [
      {
        id: 'tl-mv-1',
        time: '14:00',
        label: 'Started session',
        description: 'Opened Socket.IO connection recovery docs',
        icon: 'start',
        domain: 'socket.io',
      },
      {
        id: 'tl-mv-2',
        time: '14:20',
        label: 'Researched throttling',
        description: 'Reviewed RxJS throttleTime operators',
        icon: 'docs',
        domain: 'rxjs.dev',
      },
      {
        id: 'tl-mv-3',
        time: '14:45',
        label: 'Implemented throttling',
        description: 'Added bufferTime operator to pipeline',
        icon: 'code',
        domain: 'rxjs.dev',
      },
    ],
  },
];

export const PROJECT_HISTORY: ProjectHistory[] = [
  {
    id: 'ph-1',
    projectName: 'Smart Civic Reporter',
    lastActiveAt: 'Just now',
    sessionCount: 12,
    currentTask: 'Firebase Authentication',
    totalTabsOpened: 47,
    averageContextScore: 84,
    tags: ['Auth', 'Firebase', 'React', 'Next.js'],
    sessions: [RECENT_SESSIONS[0]],
  },
  {
    id: 'ph-2',
    projectName: 'College Assignment',
    lastActiveAt: '2 days ago',
    sessionCount: 8,
    currentTask: 'Research Paper on ML Models',
    totalTabsOpened: 31,
    averageContextScore: 72,
    tags: ['Research', 'ML', 'Python'],
    sessions: [],
  },
  {
    id: 'ph-3',
    projectName: 'Portfolio',
    lastActiveAt: '4 days ago',
    sessionCount: 5,
    currentTask: 'Hero Section Animation',
    totalTabsOpened: 18,
    averageContextScore: 91,
    tags: ['Frontend', 'CSS', 'GSAP'],
    sessions: [],
  },
  {
    id: 'ph-4',
    projectName: 'Research',
    lastActiveAt: '1 week ago',
    sessionCount: 3,
    currentTask: 'Quantum Computing Survey',
    totalTabsOpened: 22,
    averageContextScore: 68,
    tags: ['Academic', 'arXiv', 'Physics'],
    sessions: [],
  },
];

export const DEFAULT_PRIVACY_SETTINGS: PrivacySettings = {
  historyEnabled: true,
  excludedDomains: [],
  deleteSessionOnDemand: true,
  clearAllOnExit: false,
};

export const INITIAL_CONTEXT_STATE: ContextState = {
  activeProject: 'Smart Civic Reporter',
  currentTask: 'Firebase Authentication',
  contextScore: 87,
  focusState: 'Deep Work',
  switchesToday: 4,
  deepWorkMinutes: 142,
  privacyMode: 'local_only',
  openTabs: INITIAL_OPEN_TABS,
  recentSessions: RECENT_SESSIONS,
  contextSwitchEvents: [],
  tabGroups: [
    {
      groupName: 'Development',
      tabs: INITIAL_OPEN_TABS,
      primaryCategory: 'development',
      confidence: 92,
    },
  ],
  sessionStartTime: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
  lastActivityTime: new Date().toISOString(),
  projectHistory: PROJECT_HISTORY,
  privacySettings: DEFAULT_PRIVACY_SETTINGS,
};
